name: gradient_list_view
description: A Flutter package to easily add gradient fade effects to the top and bottom of any scrollable widget, making content blend seamlessly.
version: 0.1.0
homepage: https://github.com/emrhnzngn/gradient_list_view 
repository: https://github.com/emrhnzngn/gradient_list_view 
issue_tracker: https://github.com/emrhnzngn/gradient_list_view/issues 


environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0